/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Copyright (c) 2014 VigLink. Rights reserved and patent(s) pending.
*/
(function(l){var f,b={_breaker:{},each:function(a,c){var d,e;if("object"===b.type(a)&&a.hasOwnProperty)for(d in a){if(a.hasOwnProperty(d)&&c(a[d],d)===b._breaker)break}else if(a){d=0;for(e=a.length;d<e&&c(a[d],d)!==b._breaker;d++);}},extend:function(a){var c,d,b,h,g=arguments.length;a=a||{};for(d=1;d<g;d++)if(h=arguments[d],void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(a,b){try{return("function"===typeof window[b]||"object"===
typeof window[b])&&a instanceof window[b]}catch(e){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||"parentWindow"in c)?"document":c==c.window?"window":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},
attrValues:function(a,c,b){return(c=a[c])?c.split(b||" "):[]},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),b=0;return function(e,h,g){if(e){var m=e[c];if(m||void 0!==g)return m||(m=++b),a[m]||(e[c]=m,a[m]={}),void 0!==g&&(a[m][h]=g),"string"===typeof h?a[m][h]:a[m]}}}(),canonicalizeHostname:function(a){"string"===typeof a&&(a=b.createA(a));return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,
""):""},clone:function(a){return b.extend({},a)},contains:function(a,c){return-1!==b.indexOf(a,c)},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},containsPII:function(a){return/\b[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}\b/i.test(a)},contextIsAncestor:function(a,c){for(var b=a.self;b.parent&&b.parent!==b;)if(b=b.parent,b===c)return!0;return!1},cors:function(a,c,b){var e,h=function(){b?
b(e.responseText):eval(e.responseText)};e=new window.XMLHttpRequest;e.onreadystatechange=function(){4===e.readyState&&200===e.status&&h()};try{return e.open("POST",a),e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),e.withCredentials=!0,e.send(c),!0}catch(g){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,e){var h;a=(e||document).createElement(a);c=c||{};d=d||{};for(h in c)void 0!==c[h]&&(a[h]=c[h]);b.css(a,d);return a},css:function(a,
c){for(var b in c)try{a.style[b]=c[b]}catch(e){}return a},destructing:function(a){return function(a){var b=!1,e;return function(){b||(e=a.apply(null,arguments),b=!0);return e}}(a)},escapeRegExp:function(){var a;return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(e){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},exceptionLogger:function(){var a=
!1,c=b.noop;return function(b,e){if(void 0!==e)a=e,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(e){c(e)}else return b.apply(this,arguments)}}}(),find:function(a,c){var d;b.each(a,function(a,h){if(c(a,h))return d=a,b._breaker});return d},generateNodeFilter:function(){var a=function(a,b){var h,g;b=","+b.join(",")+",";h=0;for(g=a.length;h<g;h++)if(c(a[h],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],
rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(e,h){h=b.extend({ancestors:!0,self:!0},h);var g=!0,m=!0,f=function(e,h){var g;if(g=!(d.tags.length&&c(e.nodeName.toLowerCase(),d.tags))){if(g=d.classes.length){g=d.classes;var m=b.attrValues(e,"className");g=a(g,m)}if(g=!g){if(g=d.rels.length)g=d.rels,m=b.attrValues(e,"rel"),g=c(e.nodeName.toLowerCase(),",a,")&&a(g,m);g=!g&&!("function"===b.type(d.custom)&&d.custom(e,h))}}return g},m=!h.self||f(e,!0);
if(h.ancestors)for(;e.parentNode;)if(e=e.parentNode,1===e.nodeType&&!f(e,!1)){g=!1;break}return m&&g}}}(),fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,e=Infinity,h=-Infinity,g=-Infinity,m;for(a=0;a<c;a++)m=b.position(arguments[a]),d=Math.min(d,m.x),e=Math.min(e,m.y),h=Math.max(h,m.x+arguments[a].offsetWidth),
g=Math.max(g,m.y+arguments[a].offsetHeight);return{x:d,y:e,w:h-d,h:g-e,x1:d,y1:e,x2:h,y2:g}},getActualHref:function(a){return b.cache(a,"href")||a.href},hasAttrValue:function(a,c,d,e){return c?b.contains(b.attrValues(a,c,e),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},indexOf:function(){return Array.prototype.indexOf?function(a,c){return Array.prototype.indexOf.call(a,c)}:function(a,c){var b,e;b=0;for(e=a.length;b<e;b++)if(a[b]===
c)return b;return-1}}(),isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},jsonp:function(a){var c=document.getElementsByTagName("script")[0];a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c){var d=[];b.each(a,function(a,b){void 0!==a&&(d[b]=c(a))});return d},matches:function(){try{return this.Sizzle.matchesSelector.apply(this.Sizzle,
arguments)}catch(a){return!0}},on:function(){var a;return function(c,d,e){var h,g;if(1===arguments.length)a=c;else{if(2===arguments.length){if(!a)return;e=d;d=c;c=a}try{h=c["on"+d]}catch(m){}"function"===typeof h&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=h.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));g=b.exceptionLogger(function(){if(a.enabled())return e.apply(null,
arguments)});c.addEventListener?c.addEventListener(d,g,!1):c.attachEvent&&c.attachEvent("on"+d,g)}}}(),position:function(a,b){var d,e=0,h=0,g=0,m=0;b=b||document;if(!a.offsetParent)return!1;d=a;do e+=d.offsetLeft,h+=d.offsetTop,d=d.offsetParent;while(d);d=a;do g+=d.scrollLeft,m+=d.scrollTop,d=d.parentNode;while(d&&d!==b.body);return{x:e-g,y:h-m}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(b,d){(null===b||void 0===b)&&
delete a[d]});return a},ready:function(){var a=!1,c=[],d=!1,e,h,g,m,f;document.addEventListener?g=function(){document.removeEventListener("DOMContentLoaded",g,!1);f()}:document.attachEvent&&(m=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",m),f())});e=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return f();if(document.addEventListener)document.addEventListener("DOMContentLoaded",g,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
m);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&h()}b.on(window,"load",f)}};h=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.exceptionLogger(h),1);return}f()}};f=function(){if(!d){if(!document.body)return setTimeout(b.exceptionLogger(f),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){e();d?a():c.push(a)}}(),reformatKeys:function(a){var c,d,e=function(a){return"_"+a.toLowerCase()};for(c in a)d=
c.replace(/([A-Z])/g,e),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,e,h=b.attrValues(a,"className");d=0;for(e=h.length;d<e;d++)h[d]===c&&delete h[d];a.className=h.join(" ")}},request:function(a,c,d){var e,h;d=b.extend({fn:b.noop,jsonp:!0,"return":!1,timeout:null},d);"string"===typeof d.fn?(e=window[d.fn],h=d.fn):"function"===typeof d.fn&&(!0!==d.jsonp?e=d.fn:(e=b.destructing(d.fn),h=b.uniqid("vglnk_jsonp_"),
window[h]=b.exceptionLogger(function(){e.apply(this,arguments);window[h]=void 0}),null!==d.timeout&&setTimeout(b.exceptionLogger(e),d.timeout)));h&&(c=b.extend({format:"jsonp",jsonp:h},c));c=b.toQuery(c);return d["return"]?a+(c.length?"?":"")+c:b.traits.cors&&b.cors(a,c,d.jsonp?null:e)?!0:b.jsonp(a+(c.length?"?":"")+c)},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,0)}catch(b){var d,
e,h=[];d=0;for(e=a.length;d<e;d++)h[d]=a[d];return h}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},transmitsPII:function(a){return b.containsPII(a+" "+document.referrer)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(b){return(b||"")+(new Date).getTime()+a++}}()});var v=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});
a&&(b.Sizzle=a())};v.amd=!0;(function(a){function b(a,c,q,d){var e,g,h,f,m;(c?c.ownerDocument||c:C)!==B&&H(c);c=c||B;q=q||[];if(!a||"string"!==typeof a)return q;if(1!==(f=c.nodeType)&&9!==f)return[];if(D&&!d){if(e=ta.exec(a))if(h=e[1])if(9===f)if((g=c.getElementById(h))&&g.parentNode){if(g.id===h)return q.push(g),q}else return q;else{if(c.ownerDocument&&(g=c.ownerDocument.getElementById(h))&&U(c,g)&&g.id===h)return q.push(g),q}else{if(e[2])return I.apply(q,c.getElementsByTagName(a)),q;if((h=e[3])&&
w.getElementsByClassName&&c.getElementsByClassName)return I.apply(q,c.getElementsByClassName(h)),q}if(w.qsa&&(!A||!A.test(a))){g=e=z;h=c;m=9===f&&a;if(1===f&&"object"!==c.nodeName.toLowerCase()){f=t(a);(e=c.getAttribute("id"))?g=e.replace(ua,"\\$&"):c.setAttribute("id",g);g="[id='"+g+"'] ";for(h=f.length;h--;)f[h]=g+s(f[h]);h=da.test(a)&&l(c.parentNode)||c;m=f.join(",")}if(m)try{return I.apply(q,h.querySelectorAll(m)),q}catch(k){}finally{e||c.removeAttribute("id")}}}var n;a:{a=a.replace(X,"$1");g=
t(a);if(!d&&1===g.length){e=g[0]=g[0].slice(0);if(2<e.length&&"ID"===(n=e[0]).type&&w.getById&&9===c.nodeType&&D&&u.relative[e[1].type]){c=(u.find.ID(n.matches[0].replace(J,K),c)||[])[0];if(!c){n=q;break a}a=a.slice(e.shift().value.length)}for(f=Y.needsContext.test(a)?0:e.length;f--;){n=e[f];if(u.relative[h=n.type])break;if(h=u.find[h])if(d=h(n.matches[0].replace(J,K),da.test(e[0].type)&&l(c.parentNode)||c)){e.splice(f,1);a=d.length&&s(e);if(!a){I.apply(q,d);n=q;break a}break}}}ea(a,g)(d,c,!D,q,da.test(a)&&
l(c.parentNode)||c);n=q}return n}function d(){function a(c,d){b.push(c+" ")>u.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function e(a){a[z]=!0;return a}function h(a){var b=B.createElement("div");try{return!!a(b)}catch(c){return!1}finally{b.parentNode&&b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=a.length;d--;)u.attrHandle[c[d]]=b}function f(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&(~b.sourceIndex||la)-(~a.sourceIndex||la);if(d)return d;
if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function k(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function n(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function x(a){return e(function(b){b=+b;return e(function(c,d){for(var e,g=a([],c.length,b),h=g.length;h--;)if(c[e=g[h]])c[e]=!(d[e]=c[e])})})}function l(a){return a&&typeof a.getElementsByTagName!==R&&a}function r(){}function t(a,d){var q,e,g,
h,f,m,k;if(f=ma[a+" "])return d?0:f.slice(0);f=a;m=[];for(k=u.preFilter;f;){if(!q||(e=va.exec(f)))e&&(f=f.slice(e[0].length)||f),m.push(g=[]);q=!1;if(e=wa.exec(f))q=e.shift(),g.push({value:q,type:e[0].replace(X," ")}),f=f.slice(q.length);for(h in u.filter)if((e=Y[h].exec(f))&&(!k[h]||(e=k[h](e))))q=e.shift(),g.push({value:q,type:h,matches:e}),f=f.slice(q.length);if(!q)break}return d?f.length:f?b.error(a):ma(a,m).slice(0)}function s(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}function fa(a,
b,c){var d=b.dir,e=c&&"parentNode"===d,g=xa++;return b.first?function(b,c,q){for(;b=b[d];)if(1===b.nodeType||e)return a(b,c,q)}:function(b,c,q){var h,P,f,m=E+" "+g;if(q)for(;b=b[d];){if((1===b.nodeType||e)&&a(b,c,q))return!0}else for(;b=b[d];)if(1===b.nodeType||e)if(f=b[z]||(b[z]={}),(P=f[d])&&P[0]===m){if(!0===(h=P[1])||h===Z)return!0===h}else if(P=f[d]=[m],P[1]=a(b,c,q)||Z,!0===P[1])return!0}}function ga(a){return 1<a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:
a[0]}function $(a,b,c,d,e){for(var g,h=[],f=0,m=a.length,k=null!=b;f<m;f++)if(g=a[f])if(!c||c(g,d,e))h.push(g),k&&b.push(f);return h}function ha(a,d,q,g,h,f){g&&!g[z]&&(g=ha(g));h&&!h[z]&&(h=ha(h,f));return e(function(e,f,m,k){var n,l,x=[],r=[],F=f.length,y;if(!(y=e)){y=d||"*";for(var p=m.nodeType?[m]:m,t=[],Q=0,u=p.length;Q<u;Q++)b(y,p[Q],t);y=t}y=a&&(e||!d)?$(y,x,a,m,k):y;p=q?h||(e?a:F||g)?[]:f:y;q&&q(y,p,m,k);if(g){n=$(p,r);g(n,[],m,k);for(m=n.length;m--;)if(l=n[m])p[r[m]]=!(y[r[m]]=l)}if(e){if(h||
a){if(h){n=[];for(m=p.length;m--;)if(l=p[m])n.push(y[m]=l);h(null,p=[],n,k)}for(m=p.length;m--;)if((l=p[m])&&-1<(n=h?N.call(e,l):x[m]))e[n]=!(f[n]=l)}}else p=$(p===f?p.splice(F,p.length):p),h?h(null,f,p,k):I.apply(f,p)})}function ia(a){var b,c,d,e=a.length,h=u.relative[a[0].type];c=h||u.relative[" "];for(var g=h?1:0,f=fa(function(a){return a===b},c,!0),m=fa(function(a){return-1<N.call(b,a)},c,!0),k=[function(a,c,d){return!h&&(d||c!==aa)||((b=c).nodeType?f(a,c,d):m(a,c,d))}];g<e;g++)if(c=u.relative[a[g].type])k=
[fa(ga(k),c)];else{c=u.filter[a[g].type].apply(null,a[g].matches);if(c[z]){for(d=++g;d<e&&!u.relative[a[d].type];d++);return ha(1<g&&ga(k),1<g&&s(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(X,"$1"),c,g<d&&ia(a.slice(g,d)),d<e&&ia(a=a.slice(d)),d<e&&s(a))}k.push(c)}return ga(k)}function ya(a,d){var q=0,g=0<d.length,h=0<a.length,f=function(e,f,m,k,n){var l,x,r,p=0,y="0",F=e&&[],t=[],Q=aa,s=e||h&&u.find.TAG("*",n),w=E+=null==Q?1:Math.random()||0.1,A=s.length;n&&(aa=f!==B&&f,Z=q);
for(;y!==A&&null!=(l=s[y]);y++){if(h&&l){for(x=0;r=a[x++];)if(r(l,f,m)){k.push(l);break}n&&(E=w,Z=++q)}g&&((l=!r&&l)&&p--,e&&F.push(l))}p+=y;if(g&&y!==p){for(x=0;r=d[x++];)r(F,t,f,m);if(e){if(0<p)for(;y--;)!F[y]&&!t[y]&&(t[y]=za.call(k));t=$(t)}I.apply(k,t);n&&(!e&&0<t.length&&1<p+d.length)&&b.uniqueSort(k)}n&&(E=w,aa=Q);return F};return g?e(f):f}var S,w,Z,u,ba,na,ea,aa,L,T,H,B,G,D,A,O,ca,U,z="sizzle"+-new Date,C=a.document,E=0,xa=0,oa=d(),ma=d(),pa=d(),ja=function(a,b){a===b&&(T=!0);return 0},R=
"undefined",la=-2147483648,Aa={}.hasOwnProperty,M=[],za=M.pop,Ba=M.push,I=M.push,qa=M.slice,N=M.indexOf||function(a){for(var b=0,c=this.length;b<c;b++)if(this[b]===a)return b;return-1},ra="(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w#"),sa="\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)[\\x20\\t\\r\\n\\f]*(?:([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:(['\"])((?:\\\\.|[^\\\\])*?)\\3|("+ra+")|)|)[\\x20\\t\\r\\n\\f]*\\]",ka=":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\(((['\"])((?:\\\\.|[^\\\\])*?)\\3|((?:\\\\.|[^\\\\()[\\]]|"+
sa.replace(3,8)+")*)|.*)\\)|)",X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,va=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,wa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ca=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Da=RegExp(ka),Ea=RegExp("^"+ra+"$"),Y={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:RegExp("^("+"(?:\\\\.|[\\w-]|[^\\x00-\\xa0])+".replace("w","w*")+")"),ATTR:RegExp("^"+sa),PSEUDO:RegExp("^"+ka),CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)",
"i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)","i")},Fa=/^(?:input|select|textarea|button)$/i,Ga=/^h\d$/i,V=/^[^{]+\{\s*\[native \w/,ta=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,da=/[+~]/,ua=/'|\\/g,J=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,
K=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{I.apply(M=qa.call(C.childNodes),C.childNodes),M[C.childNodes.length].nodeType}catch(Ha){I={apply:M.length?function(a,b){Ba.apply(a,qa.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}w=b.support={};na=b.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};H=b.setDocument=function(a){var b=a?a.ownerDocument||
a:C;a=b.defaultView;if(b===B||9!==b.nodeType||!b.documentElement)return B;B=b;G=b.documentElement;D=!na(b);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){H()},!1):a.attachEvent&&a.attachEvent("onunload",function(){H()}));w.attributes=h(function(a){a.className="i";return!a.getAttribute("className")});w.getElementsByTagName=h(function(a){a.appendChild(b.createComment(""));return!a.getElementsByTagName("*").length});w.getElementsByClassName=V.test(b.getElementsByClassName)&&
h(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});w.getById=h(function(a){G.appendChild(a).id=z;return!b.getElementsByName||!b.getElementsByName(z).length});w.getById?(u.find.ID=function(a,b){if(typeof b.getElementById!==R&&D){var c=b.getElementById(a);return c&&c.parentNode?[c]:[]}},u.filter.ID=function(a){var b=a.replace(J,K);return function(a){return a.getAttribute("id")===b}}):(delete u.find.ID,
u.filter.ID=function(a){var b=a.replace(J,K);return function(a){return(a=typeof a.getAttributeNode!==R&&a.getAttributeNode("id"))&&a.value===b}});u.find.TAG=w.getElementsByTagName?function(a,b){if(typeof b.getElementsByTagName!==R)return b.getElementsByTagName(a)}:function(a,b){var c,d=[],e=0,g=b.getElementsByTagName(a);if("*"===a){for(;c=g[e++];)1===c.nodeType&&d.push(c);return d}return g};u.find.CLASS=w.getElementsByClassName&&function(a,b){if(typeof b.getElementsByClassName!==R&&D)return b.getElementsByClassName(a)};
O=[];A=[];if(w.qsa=V.test(b.querySelectorAll))h(function(a){a.innerHTML="<select t=''><option selected=''></option></select>";a.querySelectorAll("[t^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll(":checked").length||A.push(":checked")}),h(function(a){var c=b.createElement("input");
c.setAttribute("type","hidden");a.appendChild(c).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(w.matchesSelector=V.test(ca=G.webkitMatchesSelector||G.mozMatchesSelector||G.oMatchesSelector||G.msMatchesSelector))&&h(function(a){w.disconnectedMatch=ca.call(a,"div");ca.call(a,"[s!='']:x");O.push("!=",ka)});A=A.length&&RegExp(A.join("|"));
O=O.length&&RegExp(O.join("|"));U=(a=V.test(G.compareDocumentPosition))||V.test(G.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!(!d||!(1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};ja=a?function(a,c){if(a===c)return T=!0,0;var d=!a.compareDocumentPosition-!c.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===
(c.ownerDocument||c)?a.compareDocumentPosition(c):1;return d&1||!w.sortDetached&&c.compareDocumentPosition(a)===d?a===b||a.ownerDocument===C&&U(C,a)?-1:c===b||c.ownerDocument===C&&U(C,c)?1:L?N.call(L,a)-N.call(L,c):0:d&4?-1:1}:function(a,c){if(a===c)return T=!0,0;var d,e=0;d=a.parentNode;var g=c.parentNode,W=[a],h=[c];if(!d||!g)return a===b?-1:c===b?1:d?-1:g?1:L?N.call(L,a)-N.call(L,c):0;if(d===g)return f(a,c);for(d=a;d=d.parentNode;)W.unshift(d);for(d=c;d=d.parentNode;)h.unshift(d);for(;W[e]===h[e];)e++;
return e?f(W[e],h[e]):W[e]===C?-1:h[e]===C?1:0};return b};b.matches=function(a,d){return b(a,null,null,d)};b.matchesSelector=function(a,d){(a.ownerDocument||a)!==B&&H(a);d=d.replace(Ca,"='$1']");if(w.matchesSelector&&D&&(!O||!O.test(d))&&(!A||!A.test(d)))try{var e=ca.call(a,d);if(e||w.disconnectedMatch||a.document&&11!==a.document.nodeType)return e}catch(g){}return 0<b(d,B,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==B&&H(a);return U(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==B&&H(a);var c=u.attrHandle[b.toLowerCase()],c=c&&Aa.call(u.attrHandle,b.toLowerCase())?c(a,b,!D):void 0;return void 0!==c?c:w.attributes||!D?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;T=!w.detectDuplicates;L=!w.sortStable&&a.slice(0);a.sort(ja);if(T){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],1)}L=null;return a};ba=b.getText=
function(a){var b,c="",d=0;if(b=a.nodeType)if(1===b||9===b||11===b){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)c+=ba(a)}else{if(3===b||4===b)return a.nodeValue}else for(;b=a[d++];)c+=ba(b);return c};u=b.selectors={cacheLength:50,createPseudo:e,match:Y,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(J,
K);a[3]=(a[4]||a[5]||"").replace(J,K);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[5]&&a[2];if(Y.CHILD.test(a[0]))return null;if(a[3]&&void 0!==a[4])a[2]=a[4];else if(c&&Da.test(c)&&(b=t(c,!0))&&(b=c.indexOf(")",c.length-b)-c.length))a[0]=a[0].slice(0,
b),a[2]=c.slice(0,b);return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(J,K).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=oa[a+" "];return b||(b=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&oa(a,function(a){return b.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==R&&a.getAttribute("class")||"")})},ATTR:function(a,d,e){return function(g){g=b.attr(g,a);if(null==
g)return"!="===d;if(!d)return!0;g+="";return"="===d?g===e:"!="===d?g!==e:"^="===d?e&&0===g.indexOf(e):"*="===d?e&&-1<g.indexOf(e):"$="===d?e&&g.slice(-e.length)===e:"~="===d?-1<(" "+g+" ").indexOf(e):"|="===d?g===e||g.slice(0,e.length+1)===e+"-":!1}},CHILD:function(a,b,c,d,e){var g="nth"!==a.slice(0,3),h="last"!==a.slice(-4),f="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,m){var k,n,q,l,x;c=g!==h?"nextSibling":"previousSibling";var r=b.parentNode,p=f&&b.nodeName.toLowerCase();
m=!m&&!f;if(r){if(g){for(;c;){for(n=b;n=n[c];)if(f?n.nodeName.toLowerCase()===p:1===n.nodeType)return!1;x=c="only"===a&&!x&&"nextSibling"}return!0}x=[h?r.firstChild:r.lastChild];if(h&&m){m=r[z]||(r[z]={});k=m[a]||[];l=k[0]===E&&k[1];q=k[0]===E&&k[2];for(n=l&&r.childNodes[l];n=++l&&n&&n[c]||(q=l=0)||x.pop();)if(1===n.nodeType&&++q&&n===b){m[a]=[E,l,q];break}}else if(m&&(k=(b[z]||(b[z]={}))[a])&&k[0]===E)q=k[1];else for(;n=++l&&n&&n[c]||(q=l=0)||x.pop();)if((f?n.nodeName.toLowerCase()===p:1===n.nodeType)&&
++q)if(m&&((n[z]||(n[z]={}))[a]=[E,q]),n===b)break;q-=e;return q===d||0===q%d&&0<=q/d}}},PSEUDO:function(a,d){var g,h=u.pseudos[a]||u.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);return h[z]?h(d):1<h.length?(g=[a,a,"",d],u.setFilters.hasOwnProperty(a.toLowerCase())?e(function(a,b){for(var c,e=h(a,d),g=e.length;g--;)c=N.call(a,e[g]),a[c]=!(b[c]=e[g])}):function(a){return h(a,0,g)}):h}},pseudos:{not:e(function(a){var b=[],c=[],d=ea(a.replace(X,"$1"));return d[z]?e(function(a,b,c,e){e=
d(a,null,e,[]);for(var g=a.length;g--;)if(c=e[g])a[g]=!(b[g]=c)}):function(a,e,g){b[0]=a;d(b,null,g,c);return!c.pop()}}),has:e(function(a){return function(d){return 0<b(a,d).length}}),contains:e(function(a){return function(b){return-1<(b.textContent||b.innerText||ba(b)).indexOf(a)}}),lang:e(function(a){Ea.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(J,K).toLowerCase();return function(b){var c;do if(c=D?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),
c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===G},focus:function(a){return a===B.activeElement&&(!B.hasFocus||B.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},
selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!u.pseudos.empty(a)},header:function(a){return Ga.test(a.nodeName)},input:function(a){return Fa.test(a.nodeName)},button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==
(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:x(function(){return[0]}),last:x(function(a,b){return[b-1]}),eq:x(function(a,b,c){return[0>c?c+b:c]}),even:x(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:x(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:x(function(a,b,c){for(b=0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:x(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};u.pseudos.nth=u.pseudos.eq;for(S in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})u.pseudos[S]=
k(S);for(S in{submit:!0,reset:!0})u.pseudos[S]=n(S);r.prototype=u.filters=u.pseudos;u.setFilters=new r;ea=b.compile=function(a,b){var c,d=[],e=[],g=pa[a+" "];if(!g){b||(b=t(a));for(c=b.length;c--;)g=ia(b[c]),g[z]?d.push(g):e.push(g);g=pa(a,ya(e,d))}return g};w.sortStable=z.split("").sort(ja).join("")===z;w.detectDuplicates=!!T;H();w.sortDetached=h(function(a){return a.compareDocumentPosition(B.createElement("div"))&1});h(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||
g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});(!w.attributes||!h(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});h(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});"function"===typeof v&&v.amd?v(function(){return b}):"undefined"!==typeof module&&module.exports?module.exports=b:a.Sizzle=b})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.platforms=function(){var a={bbp:{id_finder:["div",/^post-(\d+)$/],scope:"li .post"},hdlr:{id_finder:["div",/^post_(\d+)$/],scope:".post-content-area"},ipb:{id_finder:["div",/^post_id_(\d+)$/],scope:".post_body .post"},phpb:{id_finder:["div.post",/^p(\d+)$/],scope:".postbody .content,.postbody .signature"},
ubb:{id_finder:["a",/^Post(\d+)$/,"name"],scope:".post_inner *[id^='body'],.post_inner .signature"},vb3:{id_finder:["div[id], table[id]",/^post(\d+)$/],scope:"td[id^='td_post_'] div[id^='post_message_'],td[id^='td_post_'] div[id^='post_message_'] ~ div:not([class])"},vb4:{id_finder:["li",/^post_(\d+)$/],scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{id_finder:["div",/^post-(\d+)$/],scope:null}};return function(c){return b.extend(a[c]||{},
{getPostIDs:function(){var a=[],c=this.id_finder;c&&b.each(b.select(c[0]),function(b){var g=c[2]||"id";(b=b[g]?b[g].match(c[1]):null)&&a.push(b[1])});return a.length?a:null}})}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),
quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var k,r,s;f={PLUGIN_MANUAL:1,api:function(){var a,c=b.traits.cors&&b.traits.json,d=function(a){var c={},d={};b.each(a,function(a){d[a.method]=a.opts.fn||b.noop;c[a.method]=b.prune(a.params)});h({method:"batch",params:b.extend(f.commonParams(),{batch:window.JSON.stringify(c)}),opts:{jsonp:!1,fn:function(a){g(a,d)}}})},e=function(a){try{return JSON.parse(a)}catch(b){return{}}},h=function(a){return b.request(k.api_url+
"/"+a.method,a.params,a.opts)},g=function(a,c){a=e(a);b.each(a,function(a,d){var g,h=c[d];a&&h&&("domains"===d&&"array"===b.type(a)&&(a={results:a}),a="string"===b.type(a)&&(g=a.match(/^\s*\w+\((.*)\);?\s*$/))?e("["+g[1]+"]"):[a],h.apply(window,a))})};return function(e,g,n){var l;if(1>=arguments.length)c&&(!0===arguments[0]?a=[]:a&&(1===a.length?h(a[0]):1<a.length&&d(a),a=null));else{l=b.extend(f.commonParams(e),g);l.subId&&l.key!==k.key&&(l.subId=null);l={method:e,params:l,opts:n||{}};if(l.opts["return"]||
!a)return h(l);a.push(l)}}}(),addEventListener:function(a,b){this.fire(a,b)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var h=a.open("",c);h.focus();return h}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],m=function(a,b){for(var c=a,d=c.data;(c=c[b+"Sibling"])&&3===c.nodeType;)d+=c.data;return d},k=function(a,b,c){a=a.replace(/\s+/g," ");b=b.replace(/\s+/g," ");c=c.replace(/\s+/g,
" ");a=a.replace(/^\s+/,"");" "===b.substr(0,1)&&(b=b.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===b.substr(b.length-1,1)&&(b=b.substr(0,b.length-1),c=(" "!==c.substr(0,1)?" ":"")+c);c=c.replace(/\s+$/,"");return[a,b,c]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?m(c,"previous"):"",g[2]=h&&3===h.nodeType?m(h,"next"):"",g=k.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,
10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),v:2},f.log("info",b.toQuery(a))))};return function(d,e){var h,g,f,l,n=b.context(d)||window;e=d.target||e;e=!e||e===n.name||"_top"===e&&n.top===n||"_parent"===e&&n.parent===n?"_self":e;f=a(n,e);if("_self"!==e&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))l="go";else try{if(void 0===f.document)throw!0;l="jsonp"}catch(r){l="go"}h=b.destructing(b.bind(function(){k.time_click&&
arguments.length&&this.logTime("clk");var a=b.toArray(arguments);a.unshift(d,f,e);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,e),!this.processLink(d))||!k.enabled)return h();g=this.clickParams(d,l);this.logTime();k.log_context&&c(d);if("go"===l)this.redirect(this.api("click",g,{"return":!0}),n,f,e);else if(f===n)this.api("click",g,{fn:h,timeout:k.click_timeout});else{if(b.contextIsAncestor(n,f))return this.redirect(b.getActualHref(d),
n,f,e);h=b.exceptionLogger(h);setTimeout(function(){h()},k.click_timeout);f.document.open();f.callback=h;f.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api("click",g,{fn:"callback","return":!0})+'">\x3c/script></head></html>');f.document.close()}}}(),clickParams:function(a,c){var d=b.extend(b.cache(a,"params"),{format:c,libId:k.library_id,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:k.reaffiliate||null,title:window.document.title,
txt:a.innerHTML});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:k.key?null:k.dr_key,key:k.key};("click"===a||"ping"===a)&&b.extend(c,{cuid:k.cuid,loc:location.href,subId:k.sub_id,v:1},c);return c},enabled:function(){if(k.enabled&&r!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))k.enabled=!1;return k.enabled},expose:function(a,c){if(c=c||this[a])"function"===
typeof c?c=b.exceptionLogger(b.bind(c,this)):"object"===typeof c&&(c=b.clone(c)),s[a]||(s[a]=c)},fire:function(){var a={};return function(c,d){c=c.toLowerCase();var e=a[c]||{fired:!1,listeners:[]};"function"===typeof d?e.fired?setTimeout(function(){d({type:c})},0):e.listeners.push(d):(e.fired=!0,b.each(e.listeners,function(a){"function"===typeof a&&a({type:c})}),e.listeners=[]);a[c]=e}}(),handleRightClick:function(a,c){if(k.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,
"href",a.href);a.href=this.api("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.exceptionLogger(b.bind(function(){this.handleRightClick(a,"teardown")},this)),0);break;case "teardown":a.href=b.cache(a,"href"),b.cache(a,"href",null)}},harmony:function(){b.harmony={UNSAFE_QUIRKSMODE_HANDLERS:0,LINK_LEVEL_EVENTS:-1};return function(a){return k.harmony_level<=a}}(),init:b.exceptionLogger(function(){return function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;a||(this.initLibEvents(),
this.initNamespace(),this.initOptions(),b.exceptionLogger(b.bind(this.logException,this),!k.dev),this.initProcessors(),this.initDRApi(),this.initApi(),this.enabled()&&(this.initLegacyCallbacks(),this.ping()))}}()),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);s=r[l]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",
b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("opt");this.expose("registerProcessor",function(){if(0<arguments.length)return f.registerProcessor.apply(f,arguments)});b.extend(s,s===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.exceptionLogger(b.destructing(b.bind(function(){a=!0;k.dr_key=
window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(b){window.DrivingRevenue=void 0}})},initEvents:function(a){var c={left:f.onClick,right:f.onContextmenu},d={left:b.noop,right:b.noop},e=b.traits.windowLevelHandlers?a:a.document,h=function(e){e=e||a.event;if((e=b.eventLink(e))&&!b.cache(e,"evented"))g(e,f.harmony(b.harmony.LINK_LEVEL_EVENTS)?c:d),b.cache(e,"evented",!0)},g=function(a,c){b.on(a,"click",b.bind(c.left,f));b.on(a,"contextmenu",
b.bind(c.right,f))};b.on(e,"copy",b.bind(f.onCopy,f));b.on(e,"mousedown",h);if(f.harmony(b.harmony.LINK_LEVEL_EVENTS))b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,"mousedown",h)})});(!b.traits.quirksMode||f.harmony(b.harmony.UNSAFE_QUIRKSMODE_HANDLERS))&&g(e,c)},initLegacyOptions:function(){var a,b={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in b)void 0!==window[a]&&(s[b[a]]=window[a],"vglnk_domain"===
a&&(s[b[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){k.enabled=!1}};for(a in c)window[a]=c[a]},initLibEvents:function(){b.on(f);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){b.each(b.toArray(a.document.links),b.bind(this.processLink,this))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,b=
l.split("."),d;for(l=b.pop();0<b.length;)d=b.shift(),a[d]=a[d]||{},a=a[d];r=a;s=r[l]=r[l]||{}},initOptions:function(){var a;this.initLegacyOptions();k=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,partner:null,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:0,rewrite_modified:!1,rewrite_original:!0}),k,s,{click_timeout:1E3,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,
nofollow:{},norewrite:{},plugins:{link_affiliation:{},modified_clicks:{},partner_integration:{}},time_click:!1,time_ping:!1,testing_js:[]});for(a in k)"_plugin"===a.substr(-7)&&delete k[a]},initPlugins:function(){var a,c=1,d={},e={link_affiliation:"convert",link_optimization:"optimize",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},h=function(b){return function(b){return function(){delete d[b].opts.mode;c=1;clearTimeout(a);g()}}(b)},g=function(){var e=!1,h={},k=
function(a){return function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);f.log.apply(this,c)}}};a=null;b.each(d,function(a,c){a.setup=a.setup||window.vglnk&&window.vglnk[c+"_plugin"];a.setup?(!a.run&&"function"===b.type(a.setup)&&(a.run=a.setup(a.opts,b.clone(b),s,k(a.opts.key))||b.noop),a.opts.mode===f.PLUGIN_MANUAL?h[c]=a:a.run()):(e=!0,h[c]=a)});d=h;e&&(a=setTimeout(b.exceptionLogger(g),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},k=function(){var a=!1;f.api(!0);setTimeout(function(){f.api();
a||f.api(!0)},100);g();b.on("DOMReady",function(){a=!0;setTimeout(f.api,0)})};return function(a){b.each(a,b.bind(function(a,b){b=e[b]||b;"object"===typeof a&&!1!==a.enabled&&(d[b]={opts:a},a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+b,h(b)))},this));k()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(k.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==
c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){k.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isRewritable:function(){var a=b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["norewrite",
"noskim"],custom:function(c){var e,h="";try{e=c.hostname,h=c.protocol,e.charAt(0)}catch(g){return!0}""!==e&&(e=b.canonicalizeHostname(c));return""===e||a===e||"object"===b.type(k.commercial)&&!k.commercial[e]||!h.match(/^https?:$/i)||k.norewrite[e]||!(k.rewrite_original||b.cache(c,"type"))}});return function(a){return c(a,{ancestors:!1})}}(),log:function(a,c,d,e){var h,g=b.toQuery({nocache:b.uniqid()});h="pixel.gif";if("custom"===a)g+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(e)?e:[e],
function(a){b.each(["e","i","o"],function(b){delete a[b]});g+="&"+b.toQuery(a)});else{g+="&"+b.toQuery({key:k.key,drKey:k.key?null:k.dr_key});if("time"===a)h="time.gif",a={libId:k.library_id,time:d,type:c};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;g+="&"+b.toQuery(a)}h=k.api_url+"/"+h+"?"+g;b.transmitsPII(h)||(b.createEl("img").src=h)},logException:function(a){if(k.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===
typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},logTime:function(){var a;return function(b){0===arguments.length?a=(new Date).getTime():this.log("time",b,(new Date).getTime()-a)}}(),onApiClick:function(a,c,d,e,h){var g=e||b.getActualHref(a),f=b.bind(function(){this.redirect(g,b.context(a),c,d)},this);"object"===typeof h&&(h.tracking||h.image)?(e=b.createEl(h.tracking?"iframe":"img",{src:h.tracking||h.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(e),
setTimeout(b.exceptionLogger(f),h.timeout||k.hop_timeout)):f()},onApiPing:function(a,c,d,e,h,g){k.rewrite_original=!1;h=b.reformatKeys(h||{});var m,l;e=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};l=b.extend(k.plugins,h.plugins);k=b.extend(k,h);delete k.plugins;k.library_id=a;k.click_timeout=c;k.time_ping&&this.logTime("png");"array"===b.type(k.testing_js)&&0<k.testing_js.length&&b.each(k.testing_js,function(a){b.jsonp(a)});b.extend(k.norewrite,
e(d));b.extend(k.nofollow,e(g));for(m in k)"on"===m.toLowerCase().substr(0,2)&&(2<m.length&&"function"===b.type(k[m]))&&(b.on(f,m.toLowerCase().substr(2),b.bind(k[m],window)),delete k[m]);this.initPlugins(l);this.initContext(window);this.fire("libready")},onClick:function(a){a=a||window.event;var c=a.ctrlKey||a.metaKey||a.altKey||a.shiftKey,d=a.which&&1===a.which||0===a.button,e=b.eventLink(a);if(e&&this.isRewritable(e)&&!c&&d&&!b.isDefaultPrevented(a))return this.click(e),b.preventDefault(a)},onContextmenu:function(a){(a=
b.eventLink(a||window.event))&&this.isRewritable(a)&&this.handleRightClick(a,"setup")},onCopy:function(a){var c,d,e,h=[];if(window.getSelection){d=window.getSelection();a=0;for(c=d.rangeCount;a<c;a++){try{e=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<e.length&&128>=e.length&&h.push(e)}}b.each(h,function(a){f.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,b){void 0!==b&&void 0!==this.publicOptions()[a]&&(k[a]=
b);return k[a]},ping:function(){var a=!1;return function(){if(!a&&(k.key||k.dr_key)){var c={ref:document.referrer||null};a=!0;b.transmitsPII(this.api("ping",c,{"return":!0}))||(this.logTime(),this.api("ping",c,{fn:b.bind(this.onApiPing,this)}))}}}(),processLink:function(a){if(this.isRewritable(a)){var c=b.cache(a,"processors")||{};b.each(this.registerProcessor(),function(b){c[b.id]||b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a}},publicOptions:function(){var a={};return function(c){"object"===
b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.exceptionLogger(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),e.click(),e.parentNode.removeChild(e))},registerProcessor:function(){var a=!1,c=[],d=function(d){if(void 0===
d)return c;"function"===b.type(d)&&(c.push({id:b.uniqid(),fn:d}),a&&this.initLinks())};d(function(){a=!0});return d}()};f.init();try{delete window.vglnk_self}catch(t){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,f,b){var v={},k;l=f.extend({any:!0},l);k={getDomains:function(){var l=[];f.each(v,function(b,f){l.push(f)});0<l.length&&b.api("domains",{domains:l.join("|")},{fn:f.bind(k.onDomainApi,k)})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,f.on("DOMReady",f.bind(this.getDomains,this)))}}(),onDomainApi:function(k){var l;"object"===f.type(k)&&"array"===f.type(k.results)&&(l={},f.each(k.results,function(b){l[b]=!0}),b.opt("commercial",l))},saveDomain:function(b){b=
f.canonicalizeHostname(b);v[b]=!0},setup:function(){b.opt("rewrite_original",!0);l.any||b.registerProcessor(function(b){k.initDomainLookup();k.saveDomain(b)})}};return function(){k.setup()}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,f,b){return function(){b.opt("rewrite_modified",!0)}};window.vglnk=window.vglnk||{};
window.vglnk.partners_plugin=function(l,f){var b="https:"===document.location.protocol,v={setup:function(){window._comscore=window._comscore||[]},run:function(){var k=window._comscore;k&&"function"===f.type(k.push)&&(k.push({c1:8,c2:17570528,c3:1}),f.jsonp("//"+(b?"sb":"b")+".scorecardresearch.com/beacon.js"))}};v.setup();return function(){v.run()}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,f,b){l=f.extend({key:null},l);var v={init:function(){f.each(this.getDRSearchForms(),function(b){if(!f.cache(b,"evented")){var l=v.getInput(b),s=function(){l.value||f.css(l,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};f.cache(b,"evented",!0);b.onsubmit=null;l.onfocus=null;l.onblur=null;f.on(l,"focus",function(){f.css(l,{"background-image":"none"})});f.on(l,"blur",s);s();f.on(b,"submit",function(f){v.onSubmit(f,b)})}})},
getDRSearchForms:function(){var b=[];f.each(document.getElementsByTagName("form"),function(f){v.getInput(f)&&f.id.match(/^DR-ebay-search(CSS|2)?$/i)&&b.push(f)});return b},getInput:function(b){return b.p||b.q2},onSubmit:function(k,r){k=k||window.event;var s="http://shop.ebay.com/i.html?"+f.toQuery({_nkw:v.getInput(r).value}),s=f.createA(s,"_blank");f.cache(s,"params",{key:l.key});b.click(s);return f.preventDefault(k)}};return function(){l.key&&(v.init(),f.on("DOMReady",f.bind(v.init,v)))}};
window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,f,b){var v,k={};l=f.extend({platform:null},l);v={getLinks:function(){var k=f.platforms(l.platform).getPostIDs();b.api("optimize",{pt:l.platform,i:k?k.join("|"):null,u:location.href},{fn:f.bind(v.onOptimizeApi,v)})},onOptimizeApi:function(b){"object"===f.type(b)&&"object"===f.type(b.optLinks)&&(k=b.optLinks,this.optimizeLinks({data:!0}))},optimizeLink:function(){var b=f.generateNodeFilter({classes:["nooptimize"],rels:["nooptimize"],custom:function(b,a){if(a)return Boolean(f.cache(b,
"type"))}}),l=function(b){var a=b.href,c=b.textContent||b.innerText,d=function(){var a=f.canonicalizeHostname(b);return f.canonicalizeHostname(f.createEl("a",{href:c}))===a};return{exact:a===c||function(){var a;return d()?(a=f.fromQuery(b.search),f.find(a,function(a){return a===c})):!1}(),partial:function(){var a=f.canonicalizeHostname(b);return RegExp("\\b"+f.escapeRegExp(a)+"\\b","i").test(c)}()||-1!==c.indexOf(a)}};return function(t){var a,c=k[t.href];if(c&&b(t)){a=l(t);if(a.exact){a=c.optLink;
for(var d;d=t.firstChild;)t.removeChild(d);t.appendChild(document.createTextNode(a))}else if(a.partial)return;f.cache(t,"params",{type:"LO",origOutId:c.pcid+":"+c.linkId});t.href=c.optLink}}}(),optimizeLinks:function(){var l={data:!1,timing:!1};return function(s){l=f.extend(l,s);l.timing&&(l.data&&k)&&b.registerProcessor(f.bind(this.optimizeLink,v))}}(),setup:function(){if(!l.platform||"full"===l.platform)this.getLinks();else f.on("DOMReady",f.bind(this.getLinks,this))}};v.setup();return function(){f.on("DOMReady",
function(){v.optimizeLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.page_harmony_plugin=function(l,f,b){l=f.extend({level:null},l);return function(){var f=parseInt(l.level,10);isFinite(f)&&b.opt("harmony_level",f)}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,f,b,v){var k,r,s=null,t={},a,c=0,d=0,e=0,h=0;l=f.extend({cat:null,platform:null,key:null,link_phrases:!0,link_urls:!0,link_target:null,per_page:null,per_phrase:5,product_source:null,proximity:null,same_proximity:100,scope:null,type:null,ui:!0},l);if(l.key)return k=f.platforms(l.platform),r={addPhrasesToMatcher:function(b){var c="";"regexp"===f.type(b)?c=b.source:"array"===f.type(b)&&(c="(?:^|[\\s\"'\\(])("+f.map(b,f.escapeRegExp).join("|")+")(?=\\s|\\W*$|\\W{2})");
""!==c&&(a=RegExp(a?"(?:"+c+"|"+a.source+")":c,"i"))},focusLink:function(a){a.id||(a.id=f.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPhrases:function(){var a=k.getPostIDs();b.api("insert",f.extend(r.getPartnerParams(),{cat:l.cat,mode:l.mode,pt:l.platform,ps:l.product_source,i:a?a.join("|"):null,u:location.href,type:l.type}),{fn:f.bind(r.onInsertApi,r)})},getPartnerParams:function(){var a,c,d=b.opt("partner"),e={};for(a in d)break;if(a)for(c in d[a])e[a+"_"+c]=d[a][c];
return e},initLink:function(a,c,d){if(d=l.link_target||d)a.target=d;a.rel="nofollow";a.href||(a.href=c.url);f.cache(a,"params",{exp:s,key:l.key,mid:c.mid,type:c.type||null});f.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var b={data:l.link_phrases?!1:l.link_urls,timing:!1},k=function(a,b){var c;c=f.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";f.cache(c,"type","inserted");f.cache(c,"phrase",a);l.ui&&(c.title="Link added by VigLink");
r.initLink(c,b);return c},s=function(b,g){for(var n,r,s,p,x=function(a){var b;a=!a||!l.per_phrase||!a.count||a.count<l.per_phrase;b=!l.per_page||c<l.per_page;return a&&b},v=function(a,b){var c,d,e,g,h,k,m,n,p,r,s=function(b){p.parentNode.insertBefore(a,p);p.parentNode.removeChild(p);return b},y=function(a,b,c){a=f.extend({},a);a.x1-=c;a.y1-=c;a.x2+=c;a.y2+=c;return a.x1<b.x2&&a.x2>b.x1&&a.y1<b.y2&&a.y2>b.y1};p=f.createEl("span");a.parentNode.insertBefore(p,a);p.appendChild(a);r=f.geometry(p);if(l.proximity||
l.same_proximity)for(k in t)if((m=t[k].links)&&!(t[k]===b&&!l.same_proximity||t[k]!==b&&!l.proximity)){n=t[k]===b?Math.max(l.same_proximity,l.proximity):l.proximity;c=0;for(d=m.length;c<d;c++){h=m[c].segments;e=0;for(g=h.length;e<g;e++)if(y(h[e].geometry,r,n))return s(!1)}}return s(!0)},F=function(a,b){var c,d,e,g,h={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)e=k[c],void 0===g||e.offsetTop===g.offsetTop?l.els.push(e):(h.segments.push(l),l={els:[e]}),g=
e;l.geometry=f.geometry.apply(f,l.els);h.segments.push(l);b.links=b.links||[];b.links.push(h);return b};b&&b.data&&(Boolean(s=b.data.match(/^\s+/))||Boolean(s=b.data.match(a)));)r=s[0],p=s.slice(1).join(""),n=t[p.toLowerCase()],r=b.data.indexOf(r)+r.length-p.length,0<r&&(b=b.splitText(r)),r=b.length<=p.length?null:b.splitText(p.length),p&&!n&&(n={url:p.match(/^https?:\/\//i)?p:"http://"+p,type:"U"}),p&&(x(n)&&v(b,n))&&(p=k(p,n),f.cache(p,"unlinked")||("U"===n.type?h++:"L"===n.type.toUpperCase()?d++:
e++,g(p,b),F(p,n),n.count++,c++)),b=r},n=function(b){var c=!1,d=b.parentNode,e=function(a,b){d.insertBefore(a,b);d.removeChild(b)};b.data&&(c=a.test(b.data.replace(/\s+/," ")));c&&s(b,e)},x=f.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return f.matches(a,"a[href]")}}),p=function(a){var b;if(a){if(x(a,{ancestors:!1,self:!0}))for(b=
a.firstChild;b;)a=b.nextSibling,1===b.nodeType?p(b):3===b.nodeType&&n(b),b=a}else f.each(f.select(l.scope),function(a){x(a,{ancestors:!0,self:!1})&&p(a)})};return function(c){b=f.extend(b,c);b.timing&&(b.data&&a)&&(p(),r.log())}}(),loadPhrases:function(a){var b,c,d,e=[];b=0;for(c=a.length;b<c;b++)d=a[b],d.phrase&&d.url&&(d.phrase=d.phrase.toLowerCase(),t[d.phrase]||(e.push(d.phrase),t[d.phrase]={count:t[d.phrase]?t[d.phrase].count:0,phrase:d.phrase,mid:d.mid,url:d.url,type:d.type||""}));0<e.length&&
this.addPhrasesToMatcher(e);this.insertLinks({data:!0})},log:function(){var a,b,f={heavy:[],lite:[]},k=function(a,b){return b.split(",")[0]-a.split(",")[0]};for(a in t)b=parseInt(t[a].count,10),0<b&&(b=[b,a.replace(/\|/g,"%7C")].join(),f["L"===t[a].type.toUpperCase()?"lite":"heavy"].push(b));f.lite.sort(k);f.heavy.sort(k);v("insert",[{ct:c,cl:d,ch:e,cu:h,exp:s},{pl:f.lite.join("|")},{ph:f.heavy.join("|")}])},onInsertApi:function(a){"object"===f.type(a)&&(s=a.exp,a.results&&this.loadPhrases(a.results))},
setup:function(){l.scope=l.scope||k.scope||"body";l.link_urls&&this.addPhrasesToMatcher(RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))","i"));if(l.link_phrases)if(!l.platform||"full"===l.platform)this.getPhrases();else f.on("DOMReady",f.bind(this.getPhrases,
this))}},r.setup(),function(){f.on("DOMReady",function(){r.insertLinks({timing:!0})})}};window.vglnk=window.vglnk||{};window.vglnk.spotlight_plugin=function(l,f,b){window.vglnk.spotlight_plugin.exports={$:f,opts:l,vglnk:b};return function(){(!f.browser.ie||6<f.browser.version)&&f.jsonp(b.opt("asset_url")+"/spotlight.js")}};
